name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 22
          cache: gradle

      - name: Grant execute permission
        run: chmod +x Week6_Gradle/gradlew

      - name: Run MySQL Integration Tests
        working-directory: Week6_Gradle
        run: ./gradlew orderTestDB